version: "3"
volumes:
  # MongoDB data volume        
  volume_mongo:
    driver: local

services:
  # MongoDB
  mongo:
    image: mongo
    volumes:
      - volume_mongo:/data/db

  # BaaS API + Console Server
  api-console:
    image: necbaas/api-console-server
    ports:
      - 8080:8080
    depends_on:
      - mongo
    environment:
      - MONGO_SERVERS=mongodb://mongo:27017
