version: "3"
volumes:
  # MongoDB data volume        
  volume_mongo:
    driver: local

services:
  # MongoDB
  mongo:
    image: mongo
    volumes:
      - volume_mongo:/data/db

  # RabbitMQ
  rabbit:
    image: rabbitmq:3-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq

  # Fluentd
  fluentd:
    image: necbaas/baas-fluentd
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
      - CAPPED_SIZE=128m

  # BaaS API Server
  api:
    image: necbaas/api-server
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - rabbit
      - fluentd
    environment:
      - MONGO_SERVERS=mongodb://mongo:27017
      - AMQP_URI=amqp://rabbitmq:rabbitmq@rabbit:5672
      - LOG_FLUENT_HOST=fluentd

  # BaaS Console Server
  console:
    image: necbaas/console-server
    ports:
      - 8081:8080
    depends_on:
      - mongo
      - rabbit
      - fluentd
    environment:
      - MONGO_SERVERS=mongodb://mongo:27017
      - AMQP_URI=amqp://rabbitmq:rabbitmq@rabbit:5672
      - LOG_FLUENT_HOST=fluentd

  # SSE Push Server
  ssepush:
    image: necbaas/ssepush-server
    ports:
      - 8082:8080
    depends_on:
      - rabbit
    environment:
      - AMQP_URI=amqp://rabbitmq:rabbitmq@rabbit:5672

  # BaaS Cloud Functions Servers
  cloudfn:
    image: necbaas/cloudfn-server
    depends_on:
      - rabbit
      - fluentd
    environment:
      - AMQP_URI=amqp://rabbitmq:rabbitmq@rabbit:5672
      - LOG_FLUENT_HOST=fluentd
